// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: XiangQi

#include "../ui.h"
#include <stdint.h>

// 颜色选择按钮的通用事件处理函数声明
void ui_event_change_zhenyin(lv_event_t *e);

void ui_changeWin_screen_init(void) 
{
    ui_changeWin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_changeWin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_changeWin, &ui_img_win1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_changeWin, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changeR2 = lv_btn_create(ui_changeWin);
    lv_obj_set_width(ui_changeR2, 122);
    lv_obj_set_height(ui_changeR2, 34);
    lv_obj_set_x(ui_changeR2, 85);
    lv_obj_set_y(ui_changeR2, 117);
    lv_obj_set_align(ui_changeR2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changeR2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeR2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changeR2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_changeR2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "选则红棋");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label3, &ui_font_CHINESEsize25,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_changeB2 = lv_btn_create(ui_changeWin);
    lv_obj_set_width(ui_changeB2, 122);
    lv_obj_set_height(ui_changeB2, 36);
    lv_obj_set_x(ui_changeB2, -88);
    lv_obj_set_y(ui_changeB2, 117);
    lv_obj_set_align(ui_changeB2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changeB2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeB2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changeB2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_black2 = lv_label_create(ui_changeB2);
    lv_obj_set_width(ui_black2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_black2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_black2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_black2, "选择黑棋");
    lv_obj_set_style_text_color(ui_black2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_black2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_black2, &ui_font_CHINESEsize25,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_changeR2, ui_event_change_zhenyin, LV_EVENT_ALL, (void *)'r');
    lv_obj_add_event_cb(ui_changeB2, ui_event_change_zhenyin, LV_EVENT_ALL, (void *)'b');

}


