// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_LoginAndRegiste.h"
#include "ui.h"
#include "ui_helpers.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
 
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_changeWin
void ui_changeWin_screen_init(void);
lv_obj_t * ui_changeWin;
lv_obj_t * ui_changeR2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_changeB2;
lv_obj_t * ui_black2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_win1[1] = {&ui_img_win1_png};
const lv_img_dsc_t * ui_imgset_win2[1] = {&ui_img_win2_png};

int zhenyin_selected = 0;

int xiaqi = 0;  

// SCREEN: ui_gamePage
void ui_gamePage_screen_init(void);
lv_obj_t * ui_gamePage;
lv_obj_t * ui_QiPan;
lv_obj_t * ui_hang0;
lv_obj_t * ui_Button00;
lv_obj_t * ui_Button01;
lv_obj_t * ui_Button02;
lv_obj_t * ui_Button03;
lv_obj_t * ui_Button04;
lv_obj_t * ui_Button05;
lv_obj_t * ui_Button06;
lv_obj_t * ui_Button07;
lv_obj_t * ui_Button08;
lv_obj_t * ui_hang1;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button14;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button16;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Button18;
lv_obj_t * ui_hang2;
lv_obj_t * ui_Button20;
lv_obj_t * ui_Button21;
lv_obj_t * ui_Button22;
lv_obj_t * ui_Button23;
lv_obj_t * ui_Button24;
lv_obj_t * ui_Button25;
lv_obj_t * ui_Button26;
lv_obj_t * ui_Button27;
lv_obj_t * ui_Button28;
lv_obj_t * ui_hang3;
lv_obj_t * ui_Button30;
lv_obj_t * ui_Button31;
lv_obj_t * ui_Button32;
lv_obj_t * ui_Button33;
lv_obj_t * ui_Button34;
lv_obj_t * ui_Button35;
lv_obj_t * ui_Button36;
lv_obj_t * ui_Button37;
lv_obj_t * ui_Button38;
lv_obj_t * ui_hang4;
lv_obj_t * ui_Button40;
lv_obj_t * ui_Button41;
lv_obj_t * ui_Button42;
lv_obj_t * ui_Button43;
lv_obj_t * ui_Button44;
lv_obj_t * ui_Button45;
lv_obj_t * ui_Button46;
lv_obj_t * ui_Button47;
lv_obj_t * ui_Button48;
lv_obj_t * ui_hang5;
lv_obj_t * ui_Button50;
lv_obj_t * ui_Button51;
lv_obj_t * ui_Button52;
lv_obj_t * ui_Button53;
lv_obj_t * ui_Button54;
lv_obj_t * ui_Button55;
lv_obj_t * ui_Button56;
lv_obj_t * ui_Button57;
lv_obj_t * ui_Button58;
lv_obj_t * ui_hang6;
lv_obj_t * ui_Button60;
lv_obj_t * ui_Button61;
lv_obj_t * ui_Button62;
lv_obj_t * ui_Button63;
lv_obj_t * ui_Button64;
lv_obj_t * ui_Button65;
lv_obj_t * ui_Button66;
lv_obj_t * ui_Button67;
lv_obj_t * ui_Button68;
lv_obj_t * ui_hang7;
lv_obj_t * ui_Button70;
lv_obj_t * ui_Button71;
lv_obj_t * ui_Button72;
lv_obj_t * ui_Button73;
lv_obj_t * ui_Button74;
lv_obj_t * ui_Button75;
lv_obj_t * ui_Button76;
lv_obj_t * ui_Button77;
lv_obj_t * ui_Button78;
lv_obj_t * ui_hang8;
lv_obj_t * ui_Button80;
lv_obj_t * ui_Button81;
lv_obj_t * ui_Button82;
lv_obj_t * ui_Button83;
lv_obj_t * ui_Button84;
lv_obj_t * ui_Button85;
lv_obj_t * ui_Button86;
lv_obj_t * ui_Button87;
lv_obj_t * ui_Button88;
lv_obj_t * ui_hang9;
//void ui_event_Button90(lv_event_t * e);
lv_obj_t * ui_Button90;
lv_obj_t * ui_Label90;
lv_obj_t * ui_Label91;
lv_obj_t * ui_Label92;
lv_obj_t * ui_Label93;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Label95;
lv_obj_t * ui_Label96;
lv_obj_t * ui_Label97;
lv_obj_t * ui_Label98;
lv_obj_t * ui_Button91;
lv_obj_t * ui_Button92;
lv_obj_t * ui_Button93;
lv_obj_t * ui_Button94;
lv_obj_t * ui_Button95;
lv_obj_t * ui_Button96;
lv_obj_t * ui_Button97;
lv_obj_t * ui_Button98;
lv_obj_t * ui_gamewinCon;
lv_obj_t * ui_showWin;
lv_obj_t * ui_gamelowCon;
lv_obj_t * ui_showLow;

lv_obj_t * ui_Label00;
lv_obj_t * ui_Label01;
lv_obj_t * ui_Label02;
lv_obj_t * ui_Label03;
lv_obj_t * ui_Label04;
lv_obj_t * ui_Label05;
lv_obj_t * ui_Label06;
lv_obj_t * ui_Label07;
lv_obj_t * ui_Label08;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;
lv_obj_t * ui_Label56;
lv_obj_t * ui_Label57;
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label60;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label65;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Label76;
lv_obj_t * ui_Label77;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Label81;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Label84;
lv_obj_t * ui_Label85;
lv_obj_t * ui_Label86;
lv_obj_t * ui_Label87;
lv_obj_t * ui_Label88;
lv_obj_t * ui_UserInfo;
lv_obj_t * ui_myInfo;
lv_obj_t * ui_duishouInfo;

lv_obj_t * ui_duishou;
lv_obj_t * ui_duishouPanel;
lv_obj_t * ui_duishoushengyu;
lv_obj_t * ui_duishouqiziCount;
lv_obj_t * ui_duishoutime;
lv_obj_t * ui_duishoutimecount;
lv_obj_t * ui_duishoutimedanwei;
lv_obj_t * ui_duishouWinCount;
lv_obj_t * ui_duishouWin;
lv_obj_t * ui_duishoucolor;
lv_obj_t * ui_myself;
lv_obj_t * ui_woPanel;
lv_obj_t * ui_myshengyu;
lv_obj_t * ui_myqiziCount;
lv_obj_t * ui_mytime;
lv_obj_t * ui_mytimecount;
lv_obj_t * ui_mytimedanwei; 
lv_obj_t * ui_mycolor;
lv_obj_t * ui_myWin;
lv_obj_t * ui_myWinCount;
lv_obj_t * ui_changeR;
lv_obj_t * ui_red;
lv_obj_t * ui_changeB;
lv_obj_t * ui_black;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui____initial_actions0; 
const lv_img_dsc_t * ui_img_qipan[1] = {&ui_img_qipan_png};
void update_time(lv_timer_t *timer)
{
    time_t now = time(NULL);
    struct tm *info = localtime(&now);
    char time_str[50];
    const char *week_days[] = {"周一", "周二", "周三", "周四", "周五", "周六", "周日"};
    // DBG_MSG("星期: %s", week_days[info->tm_wday]);
    sprintf(time_str, "%04d 年 %02d 月 %02d 日 |\n%s          %02d:%02d:%02d |",
            info->tm_year + 1900, info->tm_mon + 1, info->tm_mday,
            week_days[info->tm_wday], info->tm_hour, info->tm_min, info->tm_sec);

    // DBG_MSG("时间: %s", time_str);
    lv_label_set_text(label_timeANDdate, time_str);
 
}
lv_obj_t *label_timeANDdate = NULL;
void init_global_time_label(void)
{
    label_timeANDdate = lv_label_create(lv_layer_top());

    lv_label_set_text(label_timeANDdate, " ");
    lv_obj_align(label_timeANDdate, LV_ALIGN_OUT_TOP_LEFT, 170, 30);
    lv_obj_set_style_text_color(label_timeANDdate, lv_color_hex(0x7E00FF), 0);
    lv_obj_set_style_text_font(label_timeANDdate, &ui_font_CHINESEsize25, 0);
    lv_obj_add_flag(label_timeANDdate, LV_OBJ_FLAG_HIDDEN); // 隐藏

    lv_timer_create(update_time, 1000, NULL);
}
 
void ui_init(void)
{

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    DBG_PRINT();
    lv_disp_set_theme(dispp, theme);
    DBG_PRINT();

        // 初始化通信线程池（2 个线程足够处理发送和接收任务）
    int ret = init_comm_thread_pool(2);
    if (ret == -1)
    {
        printf("警告：通信线程池初始化失败\n");
    }
    
    // 初始化巴法云通信（使用线程池）
    ret = init_bemfa_communication();
    if (ret == -1)
    {
        printf("警告：巴法云连接失败，将无法进行网络对弈\n");
    }
    else
    {
        printf("巴法云通信已初始化\n");
        
        // 巴法云接通后，给两个 topic 都发送重置消息
        onlysend();
        
        // 发送重置消息到红方 topic QtDQMfr0E002
        char history_cmd_red[150];
        sprintf(history_cmd_red, "cmd=2&uid=3f2d5feab40ea3844d23321f165ab2db&topic=QtDQMfr0E002&msg=move:-1,-1,-1,-1,null\r\n");
        send(bemfa_tcpfd, history_cmd_red, strlen(history_cmd_red), 0);
        printf("已发送重置消息到 红方 QtDQMfr0E002\n");
        usleep(100000);
        
        // 发送重置消息到黑方 topic cvM3doRhm002
        char history_cmd_black[150];
        sprintf(history_cmd_black, "cmd=2&uid=3f2d5feab40ea3844d23321f165ab2db&topic=cvM3doRhm002&msg=move:-1,-1,-1,-1,null\r\n");
        send(bemfa_tcpfd, history_cmd_black, strlen(history_cmd_black), 0);
        printf("已发送重置消息到 黑方 cvM3doRhm002\n");
        usleep(100000);
        
        // 恢复接收模式
        onlyrecv();
    }
   


    
    // 默认启用接收模式
    onlyrecv();
    
    // 先显示颜色选择界面
    ui_changeWin_screen_init();
    ui_gamePage_screen_init();
    lv_disp_load_scr(ui_changeWin);

   
    // 等待用户选择颜色（轮询检查）
    printf("等待用户选择颜色...\n");
    while (!zhenyin_selected)
    {
        lv_timer_handler();  // 处理 LVGL 事件
        usleep(100000);  // 100ms
    }
    

    DBG_PRINT();
    ui____initial_actions0 = lv_obj_create(NULL);
    DBG_PRINT();
   
    init_global_time_label();
    lv_timer_create(update_time, 1000, NULL);
    lv_disp_load_scr(ui_gamePage);
    DBG_PRINT();
}
