// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

// 棋子背景颜色配置（可通过宏修改）
#define CHESS_RED_COLOR    0xFF0000    // 红色背景 (RGB565 或 RGB888)
#define CHESS_BLACK_COLOR  0x000000    // 黑色背景

#include "ui_events.h"
#include "ui_helpers.h"

// 定时器
void update_time(lv_timer_t *timer);
void create_timer();
extern lv_obj_t *label_timeANDdate;
// 弹窗
void show_popup(const char *title, const char *message);

// SCREEN: ui_changeWin
void ui_changeWin_screen_init(void);
extern lv_obj_t * ui_changeWin;
extern lv_obj_t * ui_changeR2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_changeB2;
extern lv_obj_t * ui_black2;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_changeWin  
void ui_event_change_zhenyin(lv_event_t * e); 

 
LV_IMG_DECLARE(ui_img_win2_png);    // assets/Win2.png
LV_IMG_DECLARE(ui_img_qipan_png);    // assets/qipan.png
LV_IMG_DECLARE(ui_img_mubanzi_png);    // assets/mubanzi.png
LV_IMG_DECLARE(ui_img_regame_png);    // assets/regame.png
LV_IMG_DECLARE(ui_img_shengli_png);    // assets/shengli.png
LV_IMG_DECLARE(ui_img_shibai_png);    // assets/shibai.png
LV_IMG_DECLARE(ui_img_win1_png);    // assets/win1.png



LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_CHINESEsize20);
LV_FONT_DECLARE(ui_font_CHINESEsize25);




// SCREEN: ui_gamePage
 
 void ui_event_regame(lv_event_t * e);
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_gamePage_screen_init(void);
extern lv_obj_t *ui_gamePage;
extern lv_obj_t *ui_QiPan;
extern lv_obj_t *ui_hang0;
extern lv_obj_t *ui_Button00;
extern lv_obj_t *ui_Button01;
extern lv_obj_t *ui_Button02;
extern lv_obj_t *ui_Button03;
extern lv_obj_t *ui_Button04;
extern lv_obj_t *ui_Button05;
extern lv_obj_t *ui_Button06;
extern lv_obj_t *ui_Button07;
extern lv_obj_t *ui_Button08;
extern lv_obj_t *ui_hang1;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Button14;
extern lv_obj_t *ui_Button15;
extern lv_obj_t *ui_Button16;
extern lv_obj_t *ui_Button17;
extern lv_obj_t *ui_Button18;
extern lv_obj_t *ui_hang2;
extern lv_obj_t *ui_Button20;
extern lv_obj_t *ui_Button21;
extern lv_obj_t *ui_Button22;
extern lv_obj_t *ui_Button23;
extern lv_obj_t *ui_Button24;
extern lv_obj_t *ui_Button25;
extern lv_obj_t *ui_Button26;
extern lv_obj_t *ui_Button27;
extern lv_obj_t *ui_Button28;
extern lv_obj_t *ui_hang3;
extern lv_obj_t *ui_Button30;
extern lv_obj_t *ui_Button31;
extern lv_obj_t *ui_Button32;
extern lv_obj_t *ui_Button33;
extern lv_obj_t *ui_Button34;
extern lv_obj_t *ui_Button35;
extern lv_obj_t *ui_Button36;
extern lv_obj_t *ui_Button37;
extern lv_obj_t *ui_Button38;
extern lv_obj_t *ui_hang4;
extern lv_obj_t *ui_Button40;
extern lv_obj_t *ui_Button41;
extern lv_obj_t *ui_Button42;
extern lv_obj_t *ui_Button43;
extern lv_obj_t *ui_Button44;
extern lv_obj_t *ui_Button45;
extern lv_obj_t *ui_Button46;
extern lv_obj_t *ui_Button47;
extern lv_obj_t *ui_Button48;
extern lv_obj_t *ui_hang5;
extern lv_obj_t *ui_Button50;
extern lv_obj_t *ui_Button51;
extern lv_obj_t *ui_Button52;
extern lv_obj_t *ui_Button53;
extern lv_obj_t *ui_Button54;
extern lv_obj_t *ui_Button55;
extern lv_obj_t *ui_Button56;
extern lv_obj_t *ui_Button57;
extern lv_obj_t *ui_Button58;
extern lv_obj_t *ui_hang6;
extern lv_obj_t *ui_Button60;
extern lv_obj_t *ui_Button61;
extern lv_obj_t *ui_Button62;
extern lv_obj_t *ui_Button63;
extern lv_obj_t *ui_Button64;
extern lv_obj_t *ui_Button65;
extern lv_obj_t *ui_Button66;
extern lv_obj_t *ui_Button67;
extern lv_obj_t *ui_Button68;
extern lv_obj_t *ui_hang7;
extern lv_obj_t *ui_Button70;
extern lv_obj_t *ui_Button71;
extern lv_obj_t *ui_Button72;
extern lv_obj_t *ui_Button73;
extern lv_obj_t *ui_Button74;
extern lv_obj_t *ui_Button75;
extern lv_obj_t *ui_Button76;
extern lv_obj_t *ui_Button77;
extern lv_obj_t *ui_Button78;
extern lv_obj_t *ui_hang8;
extern lv_obj_t *ui_Button80;
extern lv_obj_t *ui_Button81;
extern lv_obj_t *ui_Button82;
extern lv_obj_t *ui_Button83;
extern lv_obj_t *ui_Button84;
extern lv_obj_t *ui_Button85;
extern lv_obj_t *ui_Button86;
extern lv_obj_t *ui_Button87;
extern lv_obj_t *ui_Button88;
extern lv_obj_t *ui_hang9; 
extern lv_obj_t *ui_Button90; 
extern lv_obj_t *ui_Button91;
extern lv_obj_t *ui_Button92;
extern lv_obj_t *ui_Button93;
extern lv_obj_t *ui_Button94;
extern lv_obj_t *ui_Button95;
extern lv_obj_t *ui_Button96;
extern lv_obj_t *ui_Button97;
extern lv_obj_t *ui_Button98;


extern lv_obj_t * ui_gamewinCon;
extern lv_obj_t * ui_showWin;
extern lv_obj_t * ui_gamelowCon;
extern lv_obj_t * ui_showLow;


// 棋子 Label 声明
extern lv_obj_t *ui_Label00;
extern lv_obj_t *ui_Label01;
extern lv_obj_t *ui_Label02;
extern lv_obj_t *ui_Label03;
extern lv_obj_t *ui_Label04;
extern lv_obj_t *ui_Label05;
extern lv_obj_t *ui_Label06;
extern lv_obj_t *ui_Label07;
extern lv_obj_t *ui_Label08;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_Label40;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_Label43;
extern lv_obj_t *ui_Label44;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_Label52;
extern lv_obj_t *ui_Label53;
extern lv_obj_t *ui_Label54;
extern lv_obj_t *ui_Label55;
extern lv_obj_t *ui_Label56;
extern lv_obj_t *ui_Label57;
extern lv_obj_t *ui_Label58;
extern lv_obj_t *ui_Label60;
extern lv_obj_t *ui_Label61;
extern lv_obj_t *ui_Label62;
extern lv_obj_t *ui_Label63;
extern lv_obj_t *ui_Label64;
extern lv_obj_t *ui_Label65;
extern lv_obj_t *ui_Label66;
extern lv_obj_t *ui_Label67;
extern lv_obj_t *ui_Label68;
extern lv_obj_t *ui_Label70;
extern lv_obj_t *ui_Label71;
extern lv_obj_t *ui_Label72;
extern lv_obj_t *ui_Label73;
extern lv_obj_t *ui_Label74;
extern lv_obj_t *ui_Label75;
extern lv_obj_t *ui_Label76;
extern lv_obj_t *ui_Label77;
extern lv_obj_t *ui_Label78;
extern lv_obj_t *ui_Label80;
extern lv_obj_t *ui_Label81;
extern lv_obj_t *ui_Label82;
extern lv_obj_t *ui_Label83;
extern lv_obj_t *ui_Label84;
extern lv_obj_t *ui_Label85;
extern lv_obj_t *ui_Label86;
extern lv_obj_t *ui_Label87;
extern lv_obj_t *ui_Label88;
extern lv_obj_t *ui_Label90;
extern lv_obj_t *ui_Label91;
extern lv_obj_t *ui_Label92;
extern lv_obj_t *ui_Label93;
extern lv_obj_t *ui_Label94;
extern lv_obj_t *ui_Label95;
extern lv_obj_t *ui_Label96;
extern lv_obj_t *ui_Label97;
extern lv_obj_t *ui_Label98;
extern lv_obj_t *ui_UserInfo;
extern lv_obj_t *ui_myInfo;
extern lv_obj_t *ui_duishouInfo;
extern lv_obj_t * ui_changeR;
extern lv_obj_t * ui_red;
extern lv_obj_t * ui_changeB;
extern lv_obj_t * ui_black;

extern lv_obj_t * ui_duishou;
extern lv_obj_t * ui_duishouPanel;
extern lv_obj_t * ui_duishoushengyu;
extern lv_obj_t * ui_duishouqiziCount;
extern lv_obj_t * ui_duishoutime;
extern lv_obj_t * ui_duishoutimecount;
extern lv_obj_t * ui_duishoutimedanwei;
extern lv_obj_t * ui_duishouWinCount;
extern lv_obj_t * ui_duishouWin;
extern lv_obj_t * ui_myself;
extern lv_obj_t * ui_woPanel;
extern lv_obj_t * ui_myshengyu;
extern lv_obj_t * ui_myqiziCount;
extern lv_obj_t * ui_mytime;
extern lv_obj_t * ui_mytimecount;
extern lv_obj_t * ui_mytimedanwei;
extern lv_obj_t * ui_myWin;
extern lv_obj_t * ui_myWinCount;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_qipan_png);  

LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_CHINESEsize25);

void ui_init(void);
void init_xiangqi_ui_arr(void);
extern int zhenyin_selected;
extern int xiaqi;   
lv_obj_t* get_button_by_zuobiao(int row, int col);
lv_obj_t* get_label_by_zuobiao(int row, int col);

// 巴法云通信函数
int init_bemfa_communication(void);
void close_bemfa_communication(void);
void onlyrecv(void);
void onlysend(void);
void set_current_side(int side);  // 设置当前方：0=红方，1=黑方
void send_duishou_yourcolor(int my_color);  // 通知对方选择颜色

// 全局变量
extern int bemfa_tcpfd;  // 巴法云 TCP 连接套接字

// 计时器函数
void reset_countdown_timer(void);
void start_countdown_timer(void);
void stop_countdown_timer(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
