// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
 
void ui_event_button_clicked(lv_event_t *e);

// 巴法云通信相关函数声明
int init_bemfa_communication(void);
void close_bemfa_communication(void);
void onlyrecv(void);
void send_only(void);
void set_current_side(int side);

// 线程池管理函数
int init_comm_thread_pool(int pool_size);
void destroy_comm_thread_pool(void);

void ui_event_Button1(lv_event_t * e);
void ui_event_change_zhenyin(lv_event_t * e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
